// pages/search.vue
<template>
  <div class="container">
    <Header :crumbs="[{link:'/search', text:'search'}]" />
    <div class="margined">
      <h1>search</h1>
      <form method="get">
        <input
          required
          name="q"
          type="text"
          placeholder="search query"
          ref="searchbox"
          class="input"
          :value="$route.query.q"
        />
        <select
          name="sort"
          id="sorting"
          :value="$route.query.sort || 'relevance'"
        >
          <option value="relevance">relevance</option>
          <option value="newest">newest</option>
          <option value="oldest">oldest</option>
        </select>
        <button type="submit" class="form-button">go</button>
      </form>
      <div class="speed">
        speed:
        <button @click="addParameter('content')">contains</button>
        <button @click="addParameter('title')">in title</button>
        <button @click="addParameter('username')">written by</button> 
        <button @click="addParameter('category')">in category</button> 
      </div>
      <div v-show="splash">
        <h2>search parameters</h2>
        <p>searches from scratchdb use a pretty neat format.</p>
        <p>
          each requirement is in the format <code>+requirement:"value"</code>,
          if you don't include a requirement it's assumed you mean content
        </p>

        <p>
          prefix a requirement with <code>+</code> to require it to be true,
          <code>-</code> to require it to be false and <code>~</code> if it
          should be true, but is not required
        </p>

        <table class="info">
          <thead>
            <tr>
              <th>Requirement</th>
              <th>What it does</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>username</td>
              <td>requires that the resulting posts be by a certain user</td>
            </tr>
            <tr>
              <td>category</td>
              <td>
                requires that the resulting posts be in a category (this does
                not have to be complete, +category:"Advanced" will match
                Advanced Topics)
              </td>
            </tr>
            <tr>
              <td>topic</td>
              <td>
                requires that the resulting posts be from a topic with the id
              </td>
            </tr>
            <tr>
              <td>title</td>
              <td>
                requires that the resulting posts be from a topic with a topic
                title (this does not have to be complete, +title:"help" will
                match anything with help in the title.)
              </td>
            </tr>
            <tr>
              <td>id</td>
              <td>requires that the resulting post has an id</td>
            </tr>
            <tr>
              <td>content</td>
              <td>
                requres that the resulting posts have this in their content
              </td>
            </tr>
          </tbody>
        </table>
        <br />
        <h2>other</h2>
        <p><code>/user/:username</code> will show posts by the user</p>
        <p><code>/topic/:topic</code> will show posts in a topic by id</p>
        <p><code>/post/:post</code> will show a single post by id</p>
      </div>
      <div v-show="!splash">
        <PostList :posts="data.posts" :loading="$fetchState.pending" @loadMore="loadMore()" :showLoadMore="showLoadMore"/>
      </div>
      <Footer />
    </div>
  </div>
</template>

<style scoped>
.speed {
  margin-bottom: 8px;
}

.info {
  border-collapse: collapse;
  width: 100%;
}

.info td,
.info th {
  border: 1px solid var(--table-border);
  padding: 8px;
}

.info tr:nth-child(even) {
  background-color: var(--table-stripe);
  transition: 250ms;
}

.info tr:nth-child(odd) {
  background-color: var(--background);
  transition: 250ms;
}

.info tr:hover {
  background-color: var(--table-hover);
}

.info th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: var(--brand);
  color: white;
}

@media only screen and (max-width: 800px) {
  .input {
    width: 200px;
  }
}
</style>
<script>
export default {
  head: {
    title: 'scratch forum search'
  },
  ssr: true,
  watch: {
    "$route.query": "$fetch",
  },
  data() {
    return {
      search: encodeURIComponent(decodeURIComponent(this.$route.query.q)),
      sort: encodeURIComponent(decodeURIComponent(this.$route.query.sort)),
      showLoadMore: false,
      page: 0,
      data: {},
      splash: false,
      ssr: true,
    };
  },
  methods: {
    async loadMore() {
      this.showLoadMore = false
      this.page++;
      var res = await fetch(
        `https://scratchdb.lefty.one/v3/forum/search/?q=${this.search}&o=${this.sort}&page=${this.page}`
      );

      var data = await res.json();
      this.data.posts.push(...data.posts);

      this.showLoadMore = true
    },
    addParameter(param) {
      let box = this.$refs.searchbox
      box.value += `${box.value.length == 0? '' : ' '}+${param}:""`
      box.focus()
      box.setSelectionRange(box.value.length-1, box.value.length-1);
    }
  },
  async fetch() {
    if (this.search !== "undefined") {
      this.data = await fetch(
        `https://scratchdb.lefty.one/v3/forum/search/?q=${this.search}&o=${this.sort}&page=${this.page}`
      ).then((res) => res.json());
      this.splash = false;
      this.showLoadMore = true;
      return;
    }

    this.splash = true;
  },
  fetchOnServer: false,
};
</script>

// src/routes/search.svelte
<script context="module">
	/** @type {import('@sveltejs/kit').Load} */
	import fetchWithTimeout from '$lib/fetch.js';
	export async function load({ fetch, url }) {
		const query = url.searchParams.get('q') || '';
		const sort = url.searchParams.get('sort') || 'relevance';
		const pageNumber = parseInt(url.searchParams.get('page')) || 1; // this is the pageNumber in human form, so we should substract 1 whenever talking to scratchdb

		if (query) {
			const apiURL = `https://scratchdb.lefty.one/v3/forum/search?q=${encodeURIComponent(
				query
			)}&o=${encodeURIComponent(sort)}&page=${encodeURIComponent(
				pageNumber - 1
			)}&cache=${Date.now()}`; // TODO: don't do this.

			try {
				const response = await fetchWithTimeout(apiURL, {
					timeout: 5000
				});

				const data = await response.json();
				return {
					status: response.status,
					props: {
						type: 'results',
						posts: data.posts,
						hits: data.hits,
						query,
						sort,
						pageNumber
					}
				};
			} catch (error) {
				return {
					status: 500,
					error
				};
			}
		} else {
			return {
				props: {
					type: 'home',
					posts: [],
					hits: null,
					query: '',
					sort: '',
					pageNumber: null
				}
			};
		}
	}
</script>

<script>
	import Pagination from '$lib/components/Pagination.svelte';
	import Post from '$lib/components/Post.svelte';
	import SearchForm from '$lib/components/SearchForm.svelte';

	export let type;
	export let posts;
	export let hits;

	export let query;
	export let sort;
	export let pageNumber;

	let searchInput;

	function addOperator(operator) {
		searchInput.value += `${searchInput.value.length == 0 ? '' : ' '}+${operator}:""`;
		searchInput.focus();
		searchInput.setSelectionRange(searchInput.value.length - 1, searchInput.value.length - 1);
	}
</script>

<h1>Scratch Forum Search</h1>
<SearchForm {query} {sort} bind:searchInput />

{#if type == 'home'}
	<h2>Search Parameters</h2>
	ScratchDB uses a query parser to support search operators. Each requirement is in the format +requirement:"value".
	If you don't include any operators, ScratchDB will perform a simple content search. Prefix operators
	with + to require it to be true, - to require it to be false and ~ if it should be true, but is not
	required.

	<table class="info">
		<thead>
			<tr>
				<th>Usage</th>
				<th>Results</th>
			</tr>
		</thead>
		<tbody>
			<tr
				on:click={() => {
					addOperator('content');
				}}
			>
				<td>+content:"appelmoeshapje"</td>
				<td>Requires that all results contain a certain string</td>
			</tr>
			<tr
				on:click={() => {
					addOperator('username');
				}}
			>
				<td>+username:"Jeffalo"</td>
				<td>Requires that all results are posted by a certain user</td>
			</tr>
			<tr
				on:click={() => {
					addOperator('status');
				}}
			>
				<td>+status:"Scratch Team"</td>
				<td>
					Requires that all results are posted by users of a specific Scratch rank. (New Scratcher,
					Scratcher, Scratch Team)
				</td>
			</tr>
			<tr
				on:click={() => {
					addOperator('category');
				}}
			>
				<td>+category:"Advanced Topics"</td>
				<td>
					Requires that all results are posted in a certain subforum (This does not have to be
					complete, +category:"Things" will match posts in "Things I'm Making and Creating" and "
					Things I'm Reading and Playing")
				</td>
			</tr>
			<tr
				on:click={() => {
					addOperator('topic');
				}}
			>
				<td>+topic:"446450"</td>
				<td>Requires that all results are posted in a certain topic by ID</td>
			</tr>
			<tr
				on:click={() => {
					addOperator('title');
				}}
			>
				<td>+title:"ocular"</td>
				<td>Requires that all results are posted in a certain topic by title</td>
			</tr>
			<tr
				on:click={() => {
					addOperator('closed');
				}}
			>
				<td>+closed:"0"</td>
				<td>
					Requires that all results are posted in a certain topic by closed status (0 is open, and 1
					is closed)
				</td>
			</tr>
			<tr
				on:click={() => {
					addOperator('id');
				}}
			>
				<td>+id:"5302781"</td>
				<td>Returns a single post by ID</td>
			</tr>
		</tbody>
	</table>
{:else if type == 'error'}
	<p>error</p>
{:else}
	{#if hits == 10000}
		<div class="alert warn">
			Your query resulted in over 10 thousand posts. You may have difficulty loading posts after
			page 200.
		</div>
	{/if}
	<Pagination
		currentPageNumber={pageNumber}
		total={hits}
		linkBase="/search?q={encodeURIComponent(query)}&sort={encodeURIComponent(sort)}"
		unlimited={hits == 10000}
	/>
	{#each posts as post (post.id)}
		<Post {post} />
	{/each}
	<Pagination
		currentPageNumber={pageNumber}
		total={hits}
		linkBase="/search?q={encodeURIComponent(query)}&sort={encodeURIComponent(sort)}"
		unlimited={hits == 10000}
	/>
{/if}

<style>
	.info {
		border-collapse: collapse;
		width: 100%;
		margin-top: 10px;
	}

	.info td,
	.info th {
		border: 1px solid var(--table-border);
		padding: 8px;
	}
	.info tr:nth-child(even) {
		background-color: var(--table-stripe);
		transition: 250ms;
	}
	.info tr:nth-child(odd) {
		background-color: var(--background);
		transition: 250ms;
	}
	.info tr:hover {
		background-color: var(--table-hover);
		cursor: pointer;
	}
	.info th {
		padding-top: 12px;
		padding-bottom: 12px;
		text-align: left;
		background-color: var(--brand);
		color: white;
	}
</style>
